### ISSUE TITLE
A000311 / schroeders-fourth

### ISSUE THREAD

**Issue by AlexDaniel** [ajs/perl6-Math-Sequences#101]
[A000311 / Schroeder's fourth problem; also number of phylogenetic trees with n nodes; also number of total partitions of n.](https://oeis.org/A000311)

The sequence is not implemented yet.

<code>
0 1 1 4 26 236 2752 39208 660032 12818912 282137824 6939897856 188666182784 5617349020544 181790703209728 6353726042486272 238513970965257728 9571020586419012608 408837905660444010496 18522305410364986906624
</code>

**Comment by thundergnat** [comment]
PR added https://github.com/ajs/perl6-Math-Sequences/pull/126
