### ISSUE TITLE
A000161 / partitions-two-squares

### ISSUE THREAD

**Issue by AlexDaniel** [ajs/perl6-Math-Sequences#104]
[A000161 / Number of partitions of n into 2 squares.](https://oeis.org/A000161)

The sequence is not implemented yet.

<code>
1 1 1 0 1 1 0 0 1 1 1 0 0 1 0 0 1 1 1 0 1 0 0 0 0 2 1 0 0 1 0 0 1 0 1 0 1 1 0 0 1 1 0 0 0 1 0 0 0 1 2 0 1 1 0 0 0 0 1 0 0 1 0 0 1 2 0 0 1 0 0 0 1 1 1 0 0 0 0 0 1 1 1 0 0 2 0 0 0 1 1 0 0 0 0 0 0 1 1 0 2 1 0 0 1 0 1 0
</code>

**Comment by thundergnat** [comment]
Working on this one.

**Comment by thundergnat** [comment]
Fixed with PR https://github.com/ajs/perl6-Math-Sequences/pull/122
