### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by AlexDaniel** [ajs/perl6-Math-Sequences#132]
There's no LICENSE in this repo, as far as I can see. @ajs can you please choose one and add it?

**Comment by AlexDaniel** [comment]
FWIW most @ajs's repos are MIT or Artistic 2.0 licensed, so this is almost surely just an oversight.
Contributors, please expect this repo to be licensed similarly in the future.

**Comment by ajs** [comment]
I think Artistic is most apropos. I'll add it.

**Comment by ajs** [comment]
Looks like tests are failing on master, but I'm confident that this is something @AlexDaniel is aware of. Going to merge this, since it's literally just the license.

**Comment by AlexDaniel** [comment]
@ajs thanks!

> Looks like tests are failing on master

I was checking the tests from time to time during the squashathon, and they were OK right after the event. However, it seems that the very last PR (https://github.com/ajs/perl6-Math-Sequences/pull/151) is causing some issue…

**Comment by ajs** [comment]
@AlexDaniel is the event over? Should I plan, at this point to be the gatekeeper of future issues/PRs? Also, I don't know how to contact you directly, but I'm ajs@ajs.com if you want to drop me email rather than communicating through issues/PRs...

**Comment by AlexDaniel** [comment]
> is the event over?

[Yes!](https://github.com/ajs/perl6-Math-Sequences/issues/30#issuecomment-509005868) And it was fun. FYI it lasted roughly two days around 2019-07-06. Let us know if you ever decide to extend this module beyond `core` sequences, then we can perhaps have another squashathon some time later :)
