### ISSUE TITLE
.pm files in repo

### ISSUE THREAD

**Issue by Altai-man** [ajs/perl6-Math-Sequences#44]
When the code from PRs will be sorted out, please, rename .pm files to .pm6.
It is a recommended Perl 6 extension used by tools, for example, Comma, and there are no reasons to keep the opposite.

**Comment by AlexDaniel** [comment]
@Altai-man what about `.t6`?

**Comment by Altai-man** [comment]
Don't have a strong opinion on it, though in Comma we recognize `t6` iirc.

**Comment by AlexDaniel** [comment]
Yeah, the status of `.t6` is tracked here: https://github.com/perl6/user-experience/issues/36.

If we're renaming to .pm6 might as well rename test files too.

**Comment by AlexDaniel** [comment]
I did rename the files right away. It might cause some conflicts for upcoming PRs for those who did not pull from master after the change, so please pull!
