### ISSUE TITLE
where are "ASCII equivalents?"

### ISSUE THREAD

**Issue by tbrowder** [ajs/perl6-Math-Sequences#50]
The README mentions ASCII equivalents for the four commonly-used math symbols and gives the unicode construction sequence for them, but no ASCII equivalents are shown. No such equivalents are shown in the Perl 6 docs, so maybe they do not exist.

If they do exist, they should be shown. But if they do not, can they be added to Perl 6 and then shown?

**Comment by tbrowder** [comment]
Oh, I think I see what is meant: use the class object by name instead of its symbol.

**Comment by tbrowder** [comment]
Maybe define constants like \RR, \II, \NN, and \ZZ.

**Comment by AlexDaniel** [comment]
Resolved in https://github.com/ajs/perl6-Math-Sequences/commit/b69b8cfcc7a9aa804db89aaa95ea63e55fa33ed0.
