### ISSUE TITLE
A008277 / stirling-two

### ISSUE THREAD

**Issue by AlexDaniel** [ajs/perl6-Math-Sequences#61]
[A008277 / Triangle of Stirling numbers of the second kind, S2(n,k), n >= 1, 1 <= k <= n.](https://oeis.org/A008277)

The sequence is not implemented yet.

<code>
1 1 1 1 3 1 1 7 6 1 1 15 25 10 1 1 31 90 65 15 1 1 63 301 350 140 21 1 1 127 966 1701 1050 266 28 1 1 255 3025 7770 6951 2646 462 36 1 1 511 9330 34105 42525 22827 5880 750 45 1 1 1023 28501 145750 246730 179487 63987 11880 1155 55 1
</code>

**Comment by thundergnat** [comment]
Arrg. needs to be manually closed. I copy / pastoed the issue number.
