### ISSUE TITLE
A006318 / royal-paths

### ISSUE THREAD

**Issue by AlexDaniel** [ajs/perl6-Math-Sequences#65]
[A006318 / Large Schröder numbers (or large Schroeder numbers, or big Schroeder numbers).](https://oeis.org/A006318)

The sequence is not implemented yet.

<code>
1 2 6 22 90 394 1806 8558 41586 206098 1037718 5293446 27297738 142078746 745387038 3937603038 20927156706 111818026018 600318853926 3236724317174 17518619320890 95149655201962 518431875418926 2832923350929742 15521467648875090
</code>

**Comment by thundergnat** [comment]
PR sent

In with https://github.com/ajs/perl6-Math-Sequences/pull/122
