### ISSUE TITLE
A005811 / runs

### ISSUE THREAD

**Issue by AlexDaniel** [ajs/perl6-Math-Sequences#66]
[A005811 / Number of runs in binary expansion of n (n>0); number of 1's in Gray code for n.](https://oeis.org/A005811)

The sequence is not implemented yet.

<code>
0 1 2 1 2 3 2 1 2 3 4 3 2 3 2 1 2 3 4 3 4 5 4 3 2 3 4 3 2 3 2 1 2 3 4 3 4 5 4 3 4 5 6 5 4 5 4 3 2 3 4 3 4 5 4 3 2 3 4 3 2 3 2 1 2 3 4 3 4 5 4 3 4 5 6 5 4 5 4 3 4 5 6 5 6 7 6 5 4 5 6 5 4 5
</code>

**Comment by thundergnat** [comment]
Working on this as of 16:00 UTC 2019/04/06.

**Comment by thundergnat** [comment]
Pull request pushed: 
https://github.com/ajs/perl6-Math-Sequences/pull/121
