### ISSUE TITLE
A003136 / loeschian

### ISSUE THREAD

**Issue by AlexDaniel** [ajs/perl6-Math-Sequences#74]
[A003136 / Loeschian numbers: numbers of the form x^2 + xy + y^2; norms of vectors in A2 lattice.](https://oeis.org/A003136)

The sequence is not implemented yet.

<code>
0 1 3 4 7 9 12 13 16 19 21 25 27 28 31 36 37 39 43 48 49 52 57 61 63 64 67 73 75 76 79 81 84 91 93 97 100 103 108 109 111 112 117 121 124 127 129 133 139 144 147 148 151 156 157 163 169 171 172 175 181 183 189 192
</code>

**Comment by thundergnat** [comment]
This was already fixed with PR https://github.com/ajs/perl6-Math-Sequences/pull/49

**Comment by AlexDaniel** [comment]
Thanks!
