### ISSUE TITLE
A001906 / fibonacci-bisection-sums

### ISSUE THREAD

**Issue by AlexDaniel** [ajs/perl6-Math-Sequences#82]
[A001906 / F(2n) = bisection of Fibonacci sequence: a(n) = 3*a(n-1) - a(n-2).](https://oeis.org/A001906)

The sequence is not implemented yet.

<code>
0 1 3 8 21 55 144 377 987 2584 6765 17711 46368 121393 317811 832040 2178309 5702887 14930352 39088169 102334155 267914296 701408733 1836311903 4807526976 12586269025 32951280099 86267571272 225851433717 591286729879 1548008755920
</code>

**Comment by thundergnat** [comment]
PR pushed
