### ISSUE TITLE
A001699 / binary-trees

### ISSUE THREAD

**Issue by AlexDaniel** [ajs/perl6-Math-Sequences#84]
[A001699 / Number of binary trees of height n; or products (ways to insert parentheses) of height n when multiplication is non-commutative and non-associative.](https://oeis.org/A001699)

The sequence is not implemented yet.

<code>
1 1 3 21 651 457653 210065930571 44127887745696109598901 1947270476915296449559659317606103024276803403 3791862310265926082868235028027893277370233150300118107846437701158064808916492244872560821
</code>

**Comment by thundergnat** [comment]
Working on this one

**Comment by thundergnat** [comment]
PR added.

Included in PR https://github.com/ajs/perl6-Math-Sequences/pull/122
